image: node:10

pipelines:
  branches:
    master:
      - parallel:
        - step:
            name: Lint
            script:
              - npm ci
              - npm run lint
      - step:
          size: 2x
          name: 'Build and Publish'
          script:
            - npm ci
            - npm run build

            # Publish package
            - npm publish --access=public

    feature/*:
      - parallel:
        - step:
            name: Lint
            script:
              - npm ci
              - npm run lint
        - step:
            size: 2x
            name: Build
            script:
              - npm ci
              - npm run snykprotect
              - npm run build
        - step:
            name: Snyk Test
            script:
              - npm ci
              - npm run snyktest 

